apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: nginx
        image: devops-demo-app:1.0
        ports:
        - containerPort: 80
