[master-kube]
master-kube ansible_host=18.61.35.79 ansible_user=ubuntu


[workers]
worker1-kube ansible_host=18.60.156.167 ansible_user=ubuntu

worker2-kube ansible_host=18.60.42.156 ansible_user=ubuntu
