[master-kube]
master-kube ansible_host=18.61.163.106 ansible_user=ubuntu


[workers]
worker1-kube ansible_host=98.130.45.172 ansible_user=ubuntu

worker2-kube ansible_host=16.112.69.30 ansible_user=ubuntu
